### ISSUE TITLE
raspberry3 running fail 

### ISSUE THREAD

**Issue by lunarjoll** [QuantumLiu/ComicSpider#1]
root@ka~/Market/ComicSpider# python3 download_f.py personurl.txt 0
Download comics based on file personurl.txt
Using single thread...
Traceback (most recent call last):
  File "download_f.py", line 26, in <module>
    download_from_file(path,p)
  File "download_f.py", line 14, in download_from_file
    comic=Comic(l)
  File "/root/Market/ComicSpider/comic.py", line 139, in __init__
    n_comic_title,self.des,self.cover,self.chapter_urls=self.get_info()
  File "/root/Market/ComicSpider/comic.py", line 168, in get_info
    title=re.findall(r_title,text)[0]
IndexError: list index out of range

**Comment by lunarjoll** [comment]
这是我在下载春物的时候的错误，目测是标题太长
https://manhua.dmzj.com/guoranwodeqingchunlianaixijugaocuolecomic

**Comment by lunarjoll** [comment]
这是我下载默认URL的时候
ftpuser@ka:~/upload/ComicSpider$ python3 download_f.py url.txt 0
Download comics based on file url.txt
Using single thread...
There are 19 chapters in comic 三位一体V2
Downloading all chapters of comic 三位一体V2 into dir /home/ftpuser/upload/ComicSpider/三位一体V2
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Traceback (most recent call last):
  File "/home/ftpuser/upload/ComicSpider/comic.py", line 51, in get_pages
    driver = webdriver.PhantomJS(desired_capabilities=dcap)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: 1

Traceback (most recent call last):
  File "download_f.py", line 26, in <module>
    download_from_file(path,p)
  File "download_f.py", line 15, in download_from_file
    comic.download_all_chapters_s(p)
  File "/home/ftpuser/upload/ComicSpider/comic.py", line 231, in download_all_chapters_s
    [self.download_chapter(key=title,p=p) for title in self.chapters.keys()]
  File "/home/ftpuser/upload/ComicSpider/comic.py", line 231, in <listcomp>
    [self.download_chapter(key=title,p=p) for title in self.chapters.keys()]
  File "/home/ftpuser/upload/ComicSpider/comic.py", line 222, in download_chapter
    self.pages+=self.chapters[key].get_pages()
  File "/home/ftpuser/upload/ComicSpider/comic.py", line 62, in get_pages
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
